# This is a basic workflow to help you get started with Actions
#

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
#      - uses: nuget/setup-nuget@v1
#        with:
#          nuget-api-key: ${{ secrets.NuGetAPIKey}}
#          nuget-version: '4.3.0'
#      - name: NuGet Restore
#        run: nuget restore NHLStats.sln
      - name: Run Git2SemVer
        run: echo "::set-output name=SEM_VER::$(npx -q git2semver)"
#        run: npx -q git2semver --formatter majorminorpatch-pipelines-variables-and-label
      - name: Git Semantic Version
        # You may pin to the exact commit or the version.
        # uses: PaulHatch/semantic-version@1f05445eedfefd72938a40281fa9118ea3204664
        uses: PaulHatch/semantic-version@v3.1.2
        with:
          # The branch name
          branch: "master"
          # The prefix to use to identify tags
          # tag_prefix: "v"
          # A string which, if present in a git commit, indicates that a change represents a major (breaking) change
          major_pattern: "major:"
          # A string which, if present in a git commit, indicates that a change represents a minor (feature) change
          minor_pattern: "minor:"
          # A string which, if present in a git commit, indicates that a change represents a minor (feature) change
          patch_pattern: "patch:"
          # Pattern to use when formatting output version
          format: "${major}.${minor}.${patch}"
          # Path to check for changes. If any changes are detected in the path the 'changed' output will true. Enter multiple paths separated by spaces.
          #change_path: # optional
          # Use to create a named sub-version. This value will be appended to tags created for this version.
          #namespace: # optional
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
